### PR TITLE
feat: New styling for images and embedded patterns

### PR DESCRIPTION
**Pull request by delisma**
---
name: Styling for images and embedded patterns
about: This a pull request to fix styling of images and embedded paterns
title: 'feat: New styling for images and embedded patterns'
labels: ''
assignees: '@delisma'
---

### What does this MR do?
Modify the 2020-12-17 posts to see if the styling approach for images and embedded pattern make sense

### General checklist

- [x] [Documentation](https://github.com/canada-ca/blogue-canada-ca-blog/wiki/Publishing:-3.-Approval-process) created/updated
- [x] Changelog entry added, if necessary
- [x] Tests added for this feature/bug
- [x] Conforms to the [style guides](https://www.canada.ca/en/government/about/design-system.html)

### Preview links
en: [Choosing the right button for task success](https://deploy-preview-61--blog-tbs.netlify.app/2020/12/17/choosing-buttons)
fr: [Choisir le bon bouton pour la réussite des tâches](https://deploy-preview-61--blogue-sct.netlify.app/2020/12/17/choisir-des-boutons)

### CODE REVIEW

**Comment by delisma** [comment]
@Laura Piper, @Arianna The blog posts has been modified to put images and embedded patterns in a `<figure class="thumbnail">` tag.

Two things that bother me a bit:
- When we hover on images, it looks like images can be clicked. I’ll see if the details/summary can be opened when the image is clicked
- The figures expand to the full-width of the page. I can constraint them to the width of the content with custom CSS, but meh.

**Comment by delisma** [comment]
> @LPipes4 , @arianna-merritt The blog posts has been modified to put images and embedded patterns in a `<figure class="thumbnail">` tag.
> 
> Two things that bother me a bit:
> 
> * When we hover on images, it looks like images can be clicked. I’ll see if the details/summary can be opened when the image is clicked
> * The figures expand to the full-width of the page. I can constraint them to the width of the content with custom CSS, but meh.
I was able to make the images about the same length as the text column (85 char vs 65 char) and make the background colour of the details/summary white. We still have to hover effect on the images I'll take another look later today.

**Review by arianna-merritt — CHANGES_REQUESTED** [review]
Please remove Gem file and blog.dto.btn-bak

**Comment by delisma** [comment]
@arianna-merritt I think we're good with this new pattern. I've created a CSS class `gc-complex-img` that you can put on a figure tag and will frame the image inside a white bordered box.

**Review by arianna-merritt — APPROVED** [review]
That's great. Good job!

**Pull request merged**
