### PR TITLE
Hotfix: Image components bug

### PR DESCRIPTION
**Pull request by delisma**
---
name: Image components bug
about: This a pull request to fix the parsing of the image collection based on language
title: 'Hotfix: Image components bug'
labels: 'bug'
assignees: '@delisma'
---

### General checklist

- [ ] [Documentation](README.md) created/updated
- [ ] Changelog entry added, if necessary
- [ ] Tests added for this feature/bug
- [ ] Conforms to the [style guides](https://www.canada.ca/en/government/about/design-system.html)

### CODE REVIEW

**Comment by donohuech** [comment]
Image not loading here: https://deploy-preview-123--blog-tbs.netlify.app/2021/04/08/using-interactive-questions.html

The first image on this page isn't loading, also the alt text is in English and should be in French (alt text should be: la version text suit): https://deploy-preview-123--blogue-sct.netlify.app/2020/09/18/afficher-masquer

All other images good!

**Comment by donohuech** [comment]
The same two errors are still appearing for me.

**Comment by delisma** [comment]
> The same two errors are still appearing for me.

@donohuech It should be fixed now!

**Comment by donohuech** [comment]
Everything looks good now!

**Pull request merged**
